-- CreateEnum
CREATE TYPE "Role" AS ENUM ('GENERAL_ADMIN', 'UNIVERSITY_ADMIN', 'HOSPITAL_ADMIN', 'PRECEPTOR', 'STUDENT');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'STUDENT';
